apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: zakershaha/zomato_new:latest
          tty: true
          stdin: true
          
          # --- EXTRA ENV VARIABLES FOR REACT IN DOCKER ---
          env:
            - name: CI
              value: "true"                # React build warnings ko script crash karne se rokta hai
            - name: WDS_SOCKET_PORT
              value: "0"                  # Webpack Dev Server crash fix karta hai

          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"               # Memory ko 1GB kiya taaki React boot crash na ho

          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12

          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
