apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  type: LoadBalancer  # <-- Ise 'NodePort' se hata kar 'LoadBalancer' likhein
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # Browser se open karne ke liye standard port 80
      targetPort: 3000
